module.exports = {
    extends: ['@commitlint/config-conventional'],
    rules: {
        'type-enum': [
            2,
            'always',
            [
                'feat',
                'fix',
                'docs',
                'style',
                'refactor',
                'perf',
                'test',
                'build',
                'ci',
                'chore',
                'revert',
                'security',
            ],
        ],
        'scope-enum': [
            1,
            'always',
            [
                'desktop',
                'gateway',
                'auth',
                'users',
                'projects',
                'tasks',
                'notifications',
                'shared-types',
                'shared-utils',
                'ui-components',
                'validation',
                'prisma',
                'docker',
                'ci',
                'docs',
                'deps',
            ],
        ],
        'subject-case': [2, 'never', ['sentence-case', 'start-case', 'pascal-case', 'upper-case']],
        'subject-max-length': [2, 'always', 100],
        'body-max-line-length': [1, 'always', 200],
    },
};
